/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as HomeImport } from './routes/home'
import { Route as AdminImport } from './routes/admin'
import { Route as LayoutImport } from './routes/_layout'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as AdminPostsImport } from './routes/admin/posts'
import { Route as AdminMessagesImport } from './routes/admin/messages'
import { Route as LayoutAuthImport } from './routes/_layout/auth'
import { Route as LayoutAboutImport } from './routes/_layout/about'
import { Route as LayoutAuthIndexImport } from './routes/_layout/auth/index'
import { Route as LayoutAuthRegisterImport } from './routes/_layout/auth/register'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const HomeRoute = HomeImport.update({
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const AdminPostsRoute = AdminPostsImport.update({
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)

const AdminMessagesRoute = AdminMessagesImport.update({
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)

const LayoutAuthRoute = LayoutAuthImport.update({
  path: '/auth',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAboutRoute = LayoutAboutImport.update({
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAuthIndexRoute = LayoutAuthIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutAuthRoute,
} as any)

const LayoutAuthRegisterRoute = LayoutAuthRegisterImport.update({
  path: '/register',
  getParentRoute: () => LayoutAuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/auth': {
      id: '/_layout/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof LayoutAuthImport
      parentRoute: typeof LayoutImport
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesImport
      parentRoute: typeof AdminImport
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsImport
      parentRoute: typeof AdminImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminImport
    }
    '/_layout/auth/register': {
      id: '/_layout/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof LayoutAuthRegisterImport
      parentRoute: typeof LayoutAuthImport
    }
    '/_layout/auth/': {
      id: '/_layout/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof LayoutAuthIndexImport
      parentRoute: typeof LayoutAuthImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  LayoutRoute: LayoutRoute.addChildren({
    LayoutAboutRoute,
    LayoutAuthRoute: LayoutAuthRoute.addChildren({
      LayoutAuthRegisterRoute,
      LayoutAuthIndexRoute,
    }),
    LayoutIndexRoute,
  }),
  AdminRoute: AdminRoute.addChildren({
    AdminMessagesRoute,
    AdminPostsRoute,
    AdminIndexRoute,
  }),
  HomeRoute,
  LoginRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/admin",
        "/home",
        "/login"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/about",
        "/_layout/auth",
        "/_layout/"
      ]
    },
    "/admin": {
      "filePath": "admin.tsx",
      "children": [
        "/admin/messages",
        "/admin/posts",
        "/admin/"
      ]
    },
    "/home": {
      "filePath": "home.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_layout/about": {
      "filePath": "_layout/about.tsx",
      "parent": "/_layout"
    },
    "/_layout/auth": {
      "filePath": "_layout/auth.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/auth/register",
        "/_layout/auth/"
      ]
    },
    "/admin/messages": {
      "filePath": "admin/messages.tsx",
      "parent": "/admin"
    },
    "/admin/posts": {
      "filePath": "admin/posts.tsx",
      "parent": "/admin"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/admin/": {
      "filePath": "admin/index.tsx",
      "parent": "/admin"
    },
    "/_layout/auth/register": {
      "filePath": "_layout/auth/register.tsx",
      "parent": "/_layout/auth"
    },
    "/_layout/auth/": {
      "filePath": "_layout/auth/index.tsx",
      "parent": "/_layout/auth"
    }
  }
}
ROUTE_MANIFEST_END */
